### ISSUE TITLE
OpenFileDialog shown twice for Reflector

### ISSUE THREAD

**Issue by Muscular** [wickyhu/simple-assembly-explorer#7]
When you open a assembly and click on the reflector tab you are asked twice to locate the Reflecter executable file.
Steps to reproduce:
1) Open any file in SAE
2) Select any class and click on Reflector tab
3) Press cancel on the first OpenFileDialog
4) OpenFileDialog pops up again and press cancel again
5) Exception message shown by SAE

**Comment by SPOTBEAM** [comment]
Could not load file or assembly 'Reflector, Version=8.0.1.308, Culture=neutral, PublicKeyToken=18ca6bb8dd6a03c3' or one of its dependencies. The system cannot find the file specified.
   at SimpleAssemblyExplorer.ClassEditReflectorHandler.InitControls()
   at SimpleAssemblyExplorer.ClassEditDecompilerHandler.Init()
   at SimpleAssemblyExplorer.ClassEditDecompilerHandler.tabPage_Enter(Object sender, EventArgs e)
   at System.Windows.Forms.TabPage.OnEnter(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by wickyhu** [comment]
The last build requires Reflector 8 or you can get source to build your own version

**Comment by Muscular** [comment]
That was the text of the exception thrown after closing the OpenFileDialog. I think you misunderstood me. SAE is prompting the user twice for selecting reflector if the first time the user presses the cancel button. An example situation is where I would accidentally press Reflector tab. This would pop up the file dialog and I would press cancel. After this I would expect that I go back to Details Tab or a exception dialog would be shown but I am prompted again for selecting reflector file. I hope this explains the abnormal issue.
